// Generated by scripts/generate-tacon-extensions.mjs. Do not edit.
// All executable implementations live in their checked-in Tac-On folders.
import extension0 from "./accountability-partners/extension.server";
export const extensions = [extension0];
